language: c
compiler:
  - clang
  - gcc

env:
  - COVERAGE=true
  - COVERAGE=false;

matrix:
  exclude:
    - compiler: clang 
      env: COVERAGE=true
    - compiler: gcc
      env: COVERAGE=false

before_install:
 - sudo apt-get install check
 - sudo apt-get install -y lcov
 - gem install coveralls-lcov

# Change this to your needs
script: 
  - ./bootstrap.sh
  - ./configure --with-check && make && make check

after_success:
- if [[ $COVERAGE == 'true' ]]; 
  then 
  ./coverage.sh;
  fi
 