language: c
compiler:
  - clang
  - gcc

env:
  - COVERAGE=true
  - COVERAGE=false;

matrix:
  exclude:
    - compiler: clang 
      env: COVERAGE=true
    - compiler: gcc
      env: COVERAGE=false

before_install:
 - sudo apt-get install check
 - sudo pip install cpp-coveralls

# Change this to your needs
script: 
  - ./bootstrap.sh
  - ./configure --with-check && make && make check

after_success:
- if [[ $COVERAGE == 'true' ]]; 
  then 
  ./configure --with-check --enable-gcov && make && make check;
  coveralls --exclude-pattern ".+?\.h" --exclude-pattern "\w+/test" --gcov-options '\-lp';   
  fi
 