language: c
compiler:
  - clang
  - gcc
before_install:
 - sudo apt-get install check
 - sudo pip install cpp-coveralls

# Change this to your needs
script: 
  - ./bootstrap.sh
  - ./configure --with-check && make && make check

after_success:
- ./run_coveralls.sh
 