language: c
compiler:
  - clang
  - gcc
before_install:
 - sudo apt-get install check
 - sudo pip install cpp-coveralls

# Change this to your needs
script: 
  - ./bootstrap.sh
  - ./configure --with-check && make && make check

#coveralls, how to do this with only gcc?
after_success:
- test $CC = gcc \
  && ./run_coveralls.sh \
  && echo "Not GCC ignoring coverage test" \
 